version: "3.7"
services:
  php:
    image: ${APPNAME}:${TAG}
    build:
      context: .
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        DOCKERPORT: ${DOCKERPORT}
        APPNAME: ${APPNAME}
    ports:
      - "${HOSTPORT}:${DOCKERPORT}"
    container_name: ${APPNAME}
    environment:
      REDIS_URL: redis
    volumes:
      - ./:/var/www/html/${APPNAME}
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./config/php.ini:/etc/php7/php.ini
    command: php -S 0.0.0.0:8080
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis
    # command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
