version: "3.7" 
services:
  php:
    image: ${APPNAME}:${TAG}
    build:
      context: .
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        DOCKERPORT: ${DOCKERPORT}
        APPNAME: ${APPNAME}
    ports: 
      - "${HOSTPORT}:${DOCKERPORT}"
    container_name: ${APPNAME}
    volumes:
      - ./${APPNAME}:/var/www/html/${APPNAME}
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    # command: php-watcher server.php --signal SIGTERM --arguments localhost --arguments 8080
    command: php artisan serve --host 0.0.0.0 --port=${DOCKERPORT}
    env_file:
    - .env